### ISSUE TITLE
Installation instructions are wrong

### ISSUE THREAD

**Issue by planb788** [omkarchittar/Face_Reconstruction#1]
```shell
pip install -r requirements.txt
```
not
```shell
pip install -r requirement.txt
```

then,we need
```shell
cd ./FaceReconstruction
```
The imported image path also seems wrong. The path of imgpath is in the test_image directory, and the path of disppath is in the output directory.
Modify the corresponding image path in generate_ply.py
If cv2.error is prompted, you may need to run the following command to reinstall cv2
```shell
pip install opencv-python
```

**Comment by omkarchittar** [comment]
Thank you for pointing these out.

I have made the necessary changes and am closing this issue.
